export * from './types.ts';
export { Rng, seedState, hash01 } from './rng.ts';
export { clamp, living, npcById, matchesRole, rolesOf, L, career, addLine } from './util.ts';
export { renderLoc, renderString, formatMoney, formatNumber, toLocal, wageLocal, toBase, country, roleLabel, roleTitle, careerTitle, npcAge, capitalize } from './text.ts';
export { createLife, ageUp, summarize, zodiac, SAVE_VERSION, statPoint } from './life.ts';
export type { LifeSummary } from './life.ts';
export { currentEvent, choose, queueEvent, eligible, eventDef, resolveOutcomes, applyEffect } from './events.ts';
export { listActions, doAction } from './actions.ts';
export type { ActionView } from './actions.ts';
export { listJobs, applyJob, leaveJob, promote, taxOf, levelSalary, qualification } from './career.ts';
export type { JobOffer } from './career.ts';
export { enrollUni, enrollGrad, dropOut, tuitionCost, tuitionOptions, stageLabel, gradeLetter } from './edu.ts';
export type { TuitionPlan, TuitionOption } from './edu.ts';
export { relActionsFor, doRelAction, datingCandidates, askOut } from './relations.ts';
export type { RelActionView } from './relations.ts';
export { contract, cure, kill } from './health.ts';
export { checkCond, statValue, hasDegree } from './cond.ts';
export { makeNpc, randomAppearance, inheritAppearance } from './people.ts';
export { migrate } from './migrate.ts';
export { autoplay } from './autoplay.ts';
export type { AutoplayOpts } from './autoplay.ts';
